name: Build Rust Doc And Run tests

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-04-11
          components: rust-src, llvm-tools-preview
          target: riscv64gc-unknown-none-elf
      - name: Build doc
        run: cd os && cargo doc --no-deps --verbose --features "board_qemu"
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./os/target/riscv64gc-unknown-none-elf/doc
          destination_dir: ${{ github.ref_name }}

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-04-11
          components: rust-src, llvm-tools-preview
          target: riscv64gc-unknown-none-elf
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-binutils
          version: latest
          use-tool-cache: true
      - name: Cache QEMU
        uses: actions/cache@v3
        with:
          path: qemu-bin
          key: ${{ runner.os }}-qemu-bin
      - name: Install QEMU
        run: |
          sudo apt update
          sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0
          cd qemu-bin
          export PATH=$PATH:$(pwd)/qemu-7.0-16Ki
          qemu-system-riscv64 --version

      - name: Run usertests
        run: |
          cd qemu-bin
          export PATH=$PATH:$(pwd)/qemu-7.0-16Ki
          cd ..
          cd os && make run TEST=1
        timeout-minutes: 10

      - name: Build for k210
        run: |
          cd qemu-bin
          export PATH=$PATH:$(pwd)/qemu-7.0-16Ki
          cd ..
          cd os && make build BOARD=k210